// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.junit.Assert.*;

public class DefaultSuiteTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.addArguments("--headless");
        driver = new ChromeDriver(chromeOptions);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testSeneniumSearch() throws InterruptedException {
        driver.get("http://172.28.30.184/#/home");
        driver.manage().window().setSize(new Dimension(1936, 1031));
//    driver.findElement(By.cssSelector(".icon-gengduo")).click();
//    driver.findElement(By.cssSelector(".el-dropdown-menu__item:nth-child(4) > span")).click();
        driver.findElement(By.name("username")).click();
        driver.findElement(By.name("username")).sendKeys("superadmin");
        driver.findElement(By.name("password")).sendKeys("Fxq2020!@#");
        driver.findElement(By.cssSelector(".el-checkbox__inner")).click();
        driver.findElement(By.cssSelector(".el-button > span")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".workNotice span")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".workNotice span"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        long time = 1000;
        Thread.sleep(time);
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".taskNotice .el-menu-item"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector("#pane-1 .el-col:nth-child(1) .el-input > .el-input__inner")).click();
        driver.findElement(By.cssSelector("#pane-1 .el-col:nth-child(1) .el-input > .el-input__inner")).sendKeys("7");
        driver.findElement(By.cssSelector("#pane-1 .el-row .el-button--primary")).click();
        driver.findElement(By.cssSelector("#pane-1 .el-row .el-button--primary > span")).click();
        Thread.sleep(time);
    }
}
