// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class TestSeneniumSearchTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }

    @Test
    public void testSeneniumSearch() {
        driver.get("https://www.baidu.com/");
        driver.manage().window().setSize(new Dimension(1936, 1031));
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.id("kw")).click();
        vars.put("win5757", waitForWindow(2000));
        driver.switchTo().window(vars.get("win5757").toString());
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.linkText("使用IntelliJ idea运行selenium3.0_bangwu6488的博客-CSDN...")).click();
        vars.put("win7679", waitForWindow(2000));
        driver.switchTo().window(vars.get("win7679").toString());
    }
}
